parameters:
#    yha_main.example.class: YHA\MainBundle\Example

services:
#    yha_main.example:
#        class: %yha_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
